### ISSUE TITLE
Please add some DMA sample about Serial or other bus please.

### ISSUE THREAD

**Issue by XionWin** [stm32-rs/stm32f4xx-hal#166]
This project is cool, and I use it on my stm32f407 device. but I can't find any sample and resource about serial port DMA and SPI DMA support. our cool project support DMA or not? Should I can get some sample about these? Thanks!

**Comment by thalesfragoso** [comment]
DMA isn't yet supported, there is some work being done in https://github.com/stm32-rs/stm32f4xx-hal/pull/88, but I'm kinda busy with some other stuff at the moment, I also want to see how https://github.com/rust-embedded/embedonomicon/issues/64 goes before finishing it, since we will probably have new traits to work with.

**Comment by XionWin** [comment]
Thanks for your reply, I got it, that's ok, I can find another way to achieve this requirement. good work, hope everything goes be fine.
