### ISSUE TITLE
Why is this not called stm32f4-hal?

### ISSUE THREAD

**Issue by nickray** [stm32-rs/stm32f4xx-hal#40]
There seems to be a tradition of inserting "xx" in certain crates, which I don't know where it's coming from ;) Is there a rhyme or reason behind this? Given for instance there is the `stm32f4` crate, which contains all the devices of the series, personally I would prefer the succinctness. Asking because we are renaming `stm32l432xx-hal` from https://github.com/MabezDev/stm32l4xx-hal.

**Comment by therealprof** [comment]
There're pros and cons on both sides. I don't think it's valid to compare this to `stm32f4` because that only contains a collection of (potentially un-)related modules and IIRC the only reason so separate it by family is to cut down the already enormous size of the crates otherwise you might just put all in in one crate and call it `stm32`.

I'm curious to see how the `stm32l4-hal` crate will play out since ST is already throwing the L4+ family of MCUs into the mix which may (or may not) be a good candidate to be supported by `stm32l4-hal`, too.

And that was kind of my idea behind calling it `stm32f4xx-hal` because it is very likely that everything MCU following the current numbering scheme is going to be more or less compatible on a PAC level. If needed by a new family we can easily create another crate that will handle different versions of the peripherals.

We also toyed with the idea of dividing the hal impl in a crate per peripheral (supporting different versions of the peripherals) so you could basically easily assemble your own custom HAL impl for a MCU by simply combining the right blocks and defining the available peripheral versions, amount of peripherals and pinout.

Having said that I'm not actually too attached to the name `stm32f4xx-hal` and shortening it has been brought up a few times also in https://github.com/japaric/stm32f103xx-hal/issues/106 . If we wanted to do that renaming I'd like to hear a good plan how that is supposed to go down to be completely hassle-free and seamless for the users. If it turns out to be a royal PITA that'd be a show stopper for me.
